# Generated by Django 5.1.2 on 2024-10-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('institucion_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipoGestor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableFinanciero',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('responsable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.responsablefinanciero')),
            ],
            options={
                'unique_together': {('responsable_id', 'estudiante_id')},
            },
        ),
    ]
