# Generated by Django 5.1.2 on 2024-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='institucion_id',
            field=models.IntegerField(),
        ),
    ]
