# Generated by Django 5.1.2 on 2024-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='gestor',
            name='tipoGestor',
            field=models.CharField(choices=[(0, 'Administrativo'), (1, 'Contador'), (2, 'Gestor morosos')], max_length=50),
        ),
    ]
