# Generated by Django 5.1.2 on 2024-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_rol_alter_gestor_tipogestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='tipoGestor',
            field=models.CharField(choices=[(1, 'Administrativo'), (2, 'Contador'), (3, 'Gestor morosos')], max_length=50),
        ),
    ]
