# Generated by Django 5.1.2 on 2024-10-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_gestor_tipogestor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsableestudiante',
            unique_together=set(),
        ),
    ]
