# Generated by Django 5.1.2 on 2024-10-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_responsableestudiante_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsableestudiante',
            unique_together={('responsable_id', 'estudiante_id')},
        ),
    ]
